### ISSUE TITLE
Suggest renaming this repo to ploomber-projects or maybe proojects.

### ISSUE THREAD

**Issue by kordless** [ploomber/projects#40]
The name of this repo is "projects", but checking it out into a working code directory with "projects" in place may cause a name conflict.

Scrolling through search results for /projects repos on Github yields many results, maybe over a hundred: https://github.com/search?p=95&q=projects&type=Repositories

ploomber/proojects would be fun!

**Comment by edublancas** [comment]
hi @kordless, I appreciate the suggestion!

We have considered renaming this in the past but we'll keep it as is for the moment being since we have many links to this repo scattered in other repos, our blog, etc.

Fortunately, most users do not check out this repo directly, since they can download specific examples using the `ploomber examples` command

**Comment by kordless** [comment]
Good point, this makes sense given the client is using it!
